### ISSUE TITLE
java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by Naimadx123** [ShaneBeee/NMS-API#5]
```
[22:30:32 WARN]: [NMS-API] Skin cannot be fetched!
[22:30:32 ERROR]: Error occurred while enabling mrSkinUpdater v1.0.0-SNAPSHOT (Is it up to date?)
java.lang.NoSuchFieldError: Class net.minecraft.server.level.ServerChunkCache does not have member field 'net.minecraft.server.level.ChunkTracker chunkMap'
        at mrSkinUpdater-1.0.0-SNAPSHOT-1723588229590.jar/com.shanebeestudios.nms.api.world.entity.FakePlayer.update(FakePlayer.java:185) ~[mrSkinUpdater-1.0.0-SNAPSHOT-1723588229590.jar:?]
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[?:?]
        at mrSkinUpdater-1.0.0-SNAPSHOT-1723588229590.jar/com.shanebeestudios.nms.api.world.entity.FakePlayer.update(FakePlayer.java:203) ~[mrSkinUpdater-1.0.0-SNAPSHOT-1723588229590.jar:?]
        at mrSkinUpdater-1.0.0-SNAPSHOT-1723588229590.jar/com.shanebeestudios.nms.api.world.entity.PlayerApi.spawnFakePlayer(PlayerApi.java:112) ~[mrSkinUpdater-1.0.0-SNAPSHOT-1723588229590.jar:?]
        at mrSkinUpdater-1.0.0-SNAPSHOT-1723588229590.jar/com.shanebeestudios.nms.api.world.entity.PlayerApi.spawnFakePlayer(PlayerApi.java:65) ~[mrSkinUpdater-1.0.0-SNAPSHOT-1723588229590.jar:?]
        at mrSkinUpdater-1.0.0-SNAPSHOT-1723588229590.jar/com.shanebeestudios.nms.api.world.entity.PlayerApi.spawnFakePlayer(PlayerApi.java:49) ~[mrSkinUpdater-1.0.0-SNAPSHOT-1723588229590.jar:?]
        at mrSkinUpdater-1.0.0-SNAPSHOT-1723588229590.jar/zone.vao.mrskinupdater.MrSkinUpdater.onEnable(MrSkinUpdater.java:30) ~[mrSkinUpdater-1.0.0-SNAPSHOT-1723588229590.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-124-df3b654]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at PluginManagerPlus-2.7.4.jar/net.pinger.management.loader.PaperPluginLoaderImpl.load(PaperPluginLoaderImpl.java:40) ~[PluginManagerPlus-2.7.4.jar:?]
        at PluginManagerPlus-2.7.4.jar/net.pinger.management.plugin.PluginNodeImpl.enable(PluginNodeImpl.java:154) ~[PluginManagerPlus-2.7.4.jar:?]
        at PluginManagerPlus-2.7.4.jar/net.pinger.management.PluginManagerImpl.reloadPlugin(PluginManagerImpl.java:140) ~[PluginManagerPlus-2.7.4.jar:?]
        at PluginManagerPlus-2.7.4.jar/net.pinger.management.executors.PluginExecutor.reloadPlugin(PluginExecutor.java:64) ~[PluginManagerPlus-2.7.4.jar:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at PluginManagerPlus-2.7.4.jar/com.jonahseguin.drink.command.DrinkCommandService.finishExecution(DrinkCommandService.java:173) ~[PluginManagerPlus-2.7.4.jar:?]
        at PluginManagerPlus-2.7.4.jar/com.jonahseguin.drink.command.DrinkCommandService.executeCommand(DrinkCommandService.java:156) ~[PluginManagerPlus-2.7.4.jar:?]
        at PluginManagerPlus-2.7.4.jar/com.jonahseguin.drink.command.DrinkCommandExecutor.onCommand(DrinkCommandExecutor.java:33) ~[PluginManagerPlus-2.7.4.jar:?]
        at PluginManagerPlus-2.7.4.jar/com.jonahseguin.drink.command.DrinkCommandContainer.execute(DrinkCommandContainer.java:123) ~[PluginManagerPlus-2.7.4.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1000) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.craftbukkit.entity.CraftPlayer.performCommand(CraftPlayer.java:769) ~[paper-1.21.jar:1.21-124-df3b654]
        at PluginManagerPlus-2.7.4.jar/net.pinger.management.inventory.providers.PluginProvider.lambda$initialize$5(PluginProvider.java:183) ~[PluginManagerPlus-2.7.4.jar:?]
        at PluginManagerPlus-2.7.4.jar/io.pnger.gui.item.GuiItem.applyClick(GuiItem.java:88) ~[PluginManagerPlus-2.7.4.jar:?]
        at PluginManagerPlus-2.7.4.jar/io.pnger.gui.listener.GuiListener.lambda$onInventoryClick$5(GuiListener.java:127) ~[PluginManagerPlus-2.7.4.jar:?]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at PluginManagerPlus-2.7.4.jar/io.pnger.gui.manager.GuiManager.handleInventory(GuiManager.java:107) ~[PluginManagerPlus-2.7.4.jar:?]
        at PluginManagerPlus-2.7.4.jar/io.pnger.gui.listener.GuiListener.onInventoryClick(GuiListener.java:84) ~[PluginManagerPlus-2.7.4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor11.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-124-df3b654]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-124-df3b654]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-124-df3b654]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3122) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1629) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-124-df3b654]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:30:32 INFO]: [mrSkinUpdater] Disabling mrSkinUpdater v1.0.0-SNAPSHOT
```

**Comment by ShaneBeee** [comment]
try updated paper... I have a feeling they changed something internally.
I see you're running `paper-1.21.jar:1.21-124`
so try 1.21-130 (latest build)

Something must have changed between 124 and 130 internally, because this builds fine, so I would assume it should run.

**Comment by Naimadx123** [comment]
Ok thanks, one more thing. I have a problem with this code:
    ```
    Player fakePlayer = MrSkinUpdater.getPlugin().getFakePlayer().getServerPlayer();
    PlayerProfile fakePlayerProfile = (PlayerProfile) fakePlayer.getPlayerProfile();
   

      fakePlayerProfile.getProperties().removeIf(profileProperty -> profileProperty.getName().equals("textures"));
      fakePlayerProfile.getProperties().add(new ProfileProperty("textures", textureValue, textureSignature));

      fakePlayer.setPlayerProfile(fakePlayerProfile);
      ```
      
![image](https://github.com/user-attachments/assets/ec454987-939c-42af-a8b8-1bcc40eb2a05)

Which repository have `net.minecraft.world.entity.player.Player`?

**Comment by ShaneBeee** [comment]
that is part of Minecraft itself, so you'd have to actually have NMS imported.
You can also use `FakePlayer#getBukkitEntity()`

**Comment by Naimadx123** [comment]
There is no way to get `PlayerProfile` from `FakePlayer`?

**Comment by ShaneBeee** [comment]
I have no idea

**Comment by ShaneBeee** [comment]
> that is part of Minecraft itself, so you'd have to actually have NMS imported. You can also use `FakePlayer#getBukkitEntity()`

sorry, I said this wrong, its 
`FakePlayer#getMCPlayer().getBukkitEntity()` 
to get the Bukkit `Player`, then from there you can get the player profile
